Monads in recurring payment handling
BeyondScheme/BeyondScheme.github.io pull request #14
Opened 2016-11-20 19:01 UTC by ArturT

2016-11-20 21:15 UTC, natif requested changes

2016-11-20 21:15 UTC, natif commented on _posts/2016-11-22-monads-in-recurring-payment-handling.md
> +Maybe you heard about this weird thing called monad. Maybe you even tried to read more about the topic but you never use it in practice. Sometimes real usage examples can help to understand when migh
when it might be worth

2016-11-20 21:15 UTC, natif commented on _posts/2016-11-22-monads-in-recurring-payment-handling.md
> +I am going to show you what was my problem while working on a payment handling system. I will leave the questions like what is the monad and what are examples of monads for the end of the article bec
what my problem was

2016-11-20 21:15 UTC, natif commented on _posts/2016-11-22-monads-in-recurring-payment-handling.md
> +I am going to show you what was my problem while working on a payment handling system. I will leave the questions like what is the monad and what are examples of monads for the end of the article bec
to the end of the article

2016-11-20 21:15 UTC, natif commented on _posts/2016-11-22-monads-in-recurring-payment-handling.md
> +A while ago I was working on integration with Braintree Payments and my website so companies that are doing [optimal test suite parallelisation in ruby](https://knapsackpro.com/features?utm_source=be
Have you considered coma after my website?

2016-11-20 21:15 UTC, natif commented on _posts/2016-11-22-monads-in-recurring-payment-handling.md
> +There is great gem called [dry-monads](http://dry-rb.org/gems/dry-monads/) that have a few common monads for Ruby. We are going to use it.
there is a great

2016-11-20 21:15 UTC, natif commented on _posts/2016-11-22-monads-in-recurring-payment-handling.md
> +If you want to learn more about monads in ruby examples then definitely check presentation [Refactoring Ruby with Monads by Tom Stuart](https://www.youtube.com/watch?v=J1jYlPtkrqQ).
Ruby - should it start with capital letter?

2016-11-20 21:18 UTC, natif approved these changes

2016-11-21 16:57 UTC, Tomabana commented on _posts/2016-11-22-monads-in-recurring-payment-handling.md
> +I needed to handle a few things on the payment form.
form:

2016-11-21 17:04 UTC, Tomabana approved these changes

2016-11-22 08:12 UTC, merged